---
title: Sentiments
weight: 3
chapter: true
---

<style>#chapter p {
text-align: justify} #chapter h3 {
text-align: left}
</style>

## 3. Sentiments
To capture the attitudes for 
The following sentiment lexica were used to compute the sentiments for each tweet: 

- **_Bing_** : positive/negative word list 
- **_Syuzhet_** : word list with sentiment scores reaching from -1 to 1 
- **_Jockers-Rinker_** : combined version of the Jocker's Syuzhet lexicon and Rinker's augmented Bing lexicon 
- **_NRC_** : positive/negative word list 
- **_AFINN_** : word list with sentiments reaching on a discrete scale from -5 to 5 
- **_Novak_** : list of emojis with sentiment scores reaching from -1 to 1

Each lexicon is applied to the preprocessed text of each tweet to calculate the sentiment scores. Finally all sentiments of one time window of 24 hours - 45 minutes before a game got aggregated to one representative sentiment score which then could be used for the correlation analysis. To capture different facets of expressiveness, we generated three different aggregates:
- The average sentiment each player received at each game over all sentiments within the respective time range
- The average sentiment each player received at each game over all sentiments within the respective time range, weighted with the retweet count of each tweet
- The proportion of tweets with a negative sentiment each player received at each game over all sentiments within the respective time range

The results of the sentiment analysis are displayed in the Sentiment Analysis subpage.
